import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  records=[
    {
      "updated": 1611499761142,
      "cases": 22503873,
      "todayCases": 73980,
      "deaths": 363493,
      "todayDeaths": 1067,
      "recovered": 20926764,
      "todayRecovered": 77252,
      "active": 1213616,
      "critical": 23930,
      "casesPerOneMillion": 4861.92,
      "deathsPerOneMillion": 78.53,
      "tests": 534166398,
      "testsPerOneMillion": 115405.66,
      "population": 4628597923,
      "continent": "Asia",
      "activePerOneMillion": 262.2,
      "recoveredPerOneMillion": 4521.19,
      "criticalPerOneMillion": 5.17,
      "countries": [
        "Afghanistan",
        "Armenia",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Bhutan",
        "Brunei",
        "Cambodia",
        "China",
        "Cyprus",
        "Georgia",
        "Hong Kong",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Israel",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kuwait",
        "Kyrgyzstan",
        "Lao People's Democratic Republic",
        "Lebanon",
        "Macao",
        "Malaysia",
        "Maldives",
        "Mongolia",
        "Myanmar",
        "Nepal",
        "Oman",
        "Pakistan",
        "Palestine",
        "Philippines",
        "Qatar",
        "S. Korea",
        "Saudi Arabia",
        "Singapore",
        "Sri Lanka",
        "Syrian Arab Republic",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Timor-Leste",
        "Turkey",
        "UAE",
        "Uzbekistan",
        "Vietnam",
        "Yemen"
      ]
    },
    {
      "updated": 1611499761143,
      "cases": 29205194,
      "todayCases": 205844,
      "deaths": 616639,
      "todayDeaths": 5156,
      "recovered": 18162154,
      "todayRecovered": 133024,
      "active": 10426401,
      "critical": 34749,
      "casesPerOneMillion": 49357.5,
      "deathsPerOneMillion": 1042.14,
      "tests": 326670259,
      "testsPerOneMillion": 552080.84,
      "population": 591707291,
      "continent": "North America",
      "activePerOneMillion": 17620.88,
      "recoveredPerOneMillion": 30694.49,
      "criticalPerOneMillion": 58.73,
      "countries": [
        "Anguilla",
        "Antigua and Barbuda",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Belize",
        "Bermuda",
        "British Virgin Islands",
        "Canada",
        "Caribbean Netherlands",
        "Cayman Islands",
        "Costa Rica",
        "Cuba",
        "Curaçao",
        "Dominica",
        "Dominican Republic",
        "El Salvador",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guatemala",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Martinique",
        "Mexico",
        "Montserrat",
        "Nicaragua",
        "Panama",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin",
        "Saint Pierre Miquelon",
        "Saint Vincent and the Grenadines",
        "Sint Maarten",
        "St. Barth",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
        "USA"
      ]
    },
    {
      "updated": 1611499761144,
      "cases": 15224703,
      "todayCases": 100591,
      "deaths": 400633,
      "todayDeaths": 2101,
      "recovered": 13372888,
      "todayRecovered": 67409,
      "active": 1451182,
      "critical": 19450,
      "casesPerOneMillion": 35180.45,
      "deathsPerOneMillion": 925.76,
      "tests": 63222088,
      "testsPerOneMillion": 146090.32,
      "population": 432760271,
      "continent": "South America",
      "activePerOneMillion": 3353.32,
      "recoveredPerOneMillion": 30901.38,
      "criticalPerOneMillion": 44.94,
      "countries": [
        "Argentina",
        "Bolivia",
        "Brazil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Falkland Islands (Malvinas)",
        "French Guiana",
        "Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Uruguay",
        "Venezuela"
      ]
    },
    {
      "updated": 1611499761145,
      "cases": 28881183,
      "todayCases": 168902,
      "deaths": 662332,
      "todayDeaths": 4789,
      "recovered": 15982586,
      "todayRecovered": 132597,
      "active": 12236265,
      "critical": 29993,
      "casesPerOneMillion": 38617.08,
      "deathsPerOneMillion": 885.61,
      "tests": 416211200,
      "testsPerOneMillion": 556516.7,
      "population": 747886267,
      "continent": "Europe",
      "activePerOneMillion": 16361.13,
      "recoveredPerOneMillion": 21370.34,
      "criticalPerOneMillion": 40.1,
      "countries": [
        "Albania",
        "Andorra",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia",
        "Bulgaria",
        "Channel Islands",
        "Croatia",
        "Czechia",
        "Denmark",
        "Estonia",
        "Faroe Islands",
        "Finland",
        "France",
        "Germany",
        "Gibraltar",
        "Greece",
        "Holy See (Vatican City State)",
        "Hungary",
        "Iceland",
        "Ireland",
        "Isle of Man",
        "Italy",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "San Marino",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "UK",
        "Ukraine"
      ]
    },
    {
      "updated": 1611499761146,
      "cases": 3434479,
      "todayCases": 26475,
      "deaths": 84641,
      "todayDeaths": 775,
      "recovered": 2879164,
      "todayRecovered": 26458,
      "active": 470674,
      "critical": 2750,
      "casesPerOneMillion": 2528.19,
      "deathsPerOneMillion": 62.31,
      "tests": 28650476,
      "testsPerOneMillion": 21090.21,
      "population": 1358472683,
      "continent": "Africa",
      "activePerOneMillion": 346.47,
      "recoveredPerOneMillion": 2119.41,
      "criticalPerOneMillion": 2.02,
      "countries": [
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cameroon",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Congo",
        "Côte d'Ivoire",
        "DRC",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Ethiopia",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libyan Arab Jamahiriya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Rwanda",
        "Réunion",
        "Sao Tome and Principe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sudan",
        "Swaziland",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Western Sahara",
        "Zambia",
        "Zimbabwe"
      ]
    },
    {
      "updated": 1611499761147,
      "cases": 49852,
      "todayCases": 6,
      "deaths": 1073,
      "todayDeaths": 0,
      "recovered": 33901,
      "todayRecovered": 13,
      "active": 14878,
      "critical": 12,
      "casesPerOneMillion": 1171,
      "deathsPerOneMillion": 25.2,
      "tests": 14278619,
      "testsPerOneMillion": 335399.4,
      "population": 42571987,
      "continent": "Australia/Oceania",
      "activePerOneMillion": 349.48,
      "recoveredPerOneMillion": 796.32,
      "criticalPerOneMillion": 0.28,
      "countries": [
        "Australia",
        "Fiji",
        "French Polynesia",
        "Marshall Islands",
        "Micronesia",
        "New Caledonia",
        "New Zealand",
        "Papua New Guinea",
        "Samoa",
        "Solomon Islands",
        "Vanuatu",
        "Wallis "
      ]
    }
  ];
  getData(){
    return [...this.records];
  }
}
